### GET allLikes
GET {{host}}/likes

### GET user's likes
GET {{host}}/likes/user/1

### GET post's likes
GET {{host}}/likes/post/4

### POST a new like
POST {{host}}/likes
Content-Type: application/json

{
  "id_user": 1,
  "id_post": 7
}

### DELETE a like
DELETE {{host}}/likes
Content-Type: application/json

{
  "id_user": 1,
  "id_post": 7
}

### POST a new like
POST {{host}}/likes/toggle
Content-Type: application/json

{
  "id_user": 1,
  "id_post": 4
}